"""Interactive setup for demo-friendly runtime configuration."""

from __future__ import annotations

from pathlib import Path


DEMO_ENV_PATH = Path(__file__).resolve().parent / "demo.env"


def _ask(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    value = input(f"{prompt}{suffix}: ").strip()
    return value or default


def _ask_yes_no(prompt: str, default: bool = True) -> bool:
    default_text = "Y/n" if default else "y/N"
    value = input(f"{prompt} ({default_text}): ").strip().lower()
    if not value:
        return default
    return value in {"y", "yes", "1", "true", "是", "好"}


def _env_line(key: str, value: str) -> str:
    return f"{key}={value.strip()}"


def main() -> None:
    print("姿態警報系統展示設定")
    print("這個工具會在專案資料夾產生 demo.env，之後可用 ./run_demo.sh 啟動。")
    print("不知道的項目可以直接按 Enter 略過，之後再重新執行本工具修改。")
    print()

    use_gpio = _ask_yes_no("要啟用實體蜂鳴器與 LED 嗎", True)
    buzzer_frequency = _ask("蜂鳴器頻率 Hz", "2000")
    show_window = _ask_yes_no("要顯示攝影機視窗嗎", True)
    mark_bed_roi = _ask_yes_no("啟動時要先標記床區嗎", True)
    line_token = _ask("LINE Channel Access Token（沒有可留空）")
    line_target = _ask("LINE User ID 或 Group ID（沒有可留空）")
    discord_webhook = _ask("Discord Webhook URL（沒有可留空）")
    log_path = _ask("Log 檔案位置", "/home/pi/posture_alarm/data/posture_alarm.log")

    lines = [
        "# Demo runtime settings for posture_alarm.",
        "# Generated by setup_demo.py. Keep this file private if it contains tokens.",
        "",
        _env_line("SIMULATE_GPIO", "0" if use_gpio else "1"),
        _env_line("BUZZER_PWM_ENABLED", "1"),
        _env_line("BUZZER_PWM_FREQUENCY", buzzer_frequency),
        "",
        _env_line("SHOW_WINDOW", "1" if show_window else "0"),
        _env_line("BED_ROI_MARK_ON_START", "1" if mark_bed_roi else "0"),
        "",
        _env_line("LINE_CHANNEL_ACCESS_TOKEN", line_token),
        _env_line("LINE_TARGET_ID", line_target),
        _env_line("DISCORD_WEBHOOK_URL", discord_webhook),
        "",
        _env_line("LOG_FILE_ENABLED", "1"),
        _env_line("LOG_FILE_PATH", log_path),
        "",
    ]

    DEMO_ENV_PATH.write_text("\n".join(lines), encoding="utf-8")
    print()
    print(f"已產生：{DEMO_ENV_PATH}")
    print("啟動展示模式：./run_demo.sh")


if __name__ == "__main__":
    main()
