"""Interactive setup for demo-friendly runtime configuration."""

from __future__ import annotations

from pathlib import Path


DEMO_ENV_PATH = Path(__file__).resolve().parent / "demo.env"


def _ask(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    value = input(f"{prompt}{suffix}: ").strip()
    return value or default


def _ask_yes_no(prompt: str, default: bool = True) -> bool:
    default_text = "Y/n" if default else "y/N"
    value = input(f"{prompt} ({default_text}): ").strip().lower()
    if not value:
        return default
    return value in {"y", "yes", "1", "true"}


def _env_line(key: str, value: str) -> str:
    return f"{key}={value.strip()}"


def main() -> None:
    print("Posture Alarm demo setup")
    print("This tool creates demo.env in the project folder.")
    print("Press Enter to keep the default or leave an optional value empty.")
    print()

    use_gpio = _ask_yes_no("Enable real buzzer and LED", True)
    buzzer_frequency = _ask("Buzzer frequency in Hz", "2000")
    show_window = _ask_yes_no("Show camera window", True)
    mark_bed_roi = _ask_yes_no("Mark bed area on startup", True)
    line_token = _ask("LINE Channel Access Token (optional)")
    line_target = _ask("LINE User ID or Group ID (optional)")
    discord_webhook = _ask("Discord Webhook URL (optional)")
    log_path = _ask("Log file or folder path", "/home/pi/posture_alarm/data/posture_alarm.log")

    lines = [
        "# Demo runtime settings for posture_alarm.",
        "# Generated by setup_demo.py. Keep this file private if it contains tokens.",
        "",
        _env_line("SIMULATE_GPIO", "0" if use_gpio else "1"),
        _env_line("BUZZER_PWM_ENABLED", "1"),
        _env_line("BUZZER_PWM_FREQUENCY", buzzer_frequency),
        "",
        _env_line("SHOW_WINDOW", "1" if show_window else "0"),
        _env_line("BED_ROI_MARK_ON_START", "1" if mark_bed_roi else "0"),
        "",
        _env_line("LINE_CHANNEL_ACCESS_TOKEN", line_token),
        _env_line("LINE_TARGET_ID", line_target),
        _env_line("DISCORD_WEBHOOK_URL", discord_webhook),
        "",
        _env_line("LOG_FILE_ENABLED", "1"),
        _env_line("LOG_FILE_PATH", log_path),
        "",
    ]

    DEMO_ENV_PATH.write_text("\n".join(lines), encoding="utf-8")
    print()
    print(f"Created: {DEMO_ENV_PATH}")
    print("Start demo mode: ./run_demo.sh")


if __name__ == "__main__":
    main()
